---
# handlers file for host-init
- name: restart sshd
  service: name=sshd state=restarted
  become: yes

- name: restart chronyd
  service: name=chronyd state=restarted
  become: yes

- name: restart docker
  service: name=docker state=restarted
  become: yes

- name: restart kubelet
  service: name=kubelet state=restarted
  become: yes

- name: restart network
  service: name=NetworkManager state=restarted
  become: yes

- name: restart resolved
  service: name=resolved state=restarted
  become: yes
