---
- hosts: localhost
  become: yes
  roles:
    - localhost-init

- hosts: 'masters[0]'
  become: yes
  roles:
    - ha-loadbalance

- hosts: 'masters'
#  gather_facts: False
  become: yes
  roles:
    - k8s-masters

- hosts: 'masters'
  become: yes
  roles:
    - ha-loadbalance

- hosts: 'masters[0]'
  become: yes
  roles:
    - k8s-services

- hosts: 'masters[0]'
  become: yes
  roles:
    - role: k8s-join-command

- hosts: 'nodes'
  become: yes
  roles:
    - k8s-nodes

