---
- hosts: 'new_nodes'
  become: yes
  roles:
    - host-init

- hosts: 'masters[0]'
  become: yes
  roles:
    - role: k8s-join-command

- hosts: 'new_nodes'
  become: yes
  roles:
    - k8s-nodes
