- name: clean repo cache
  command: apt clean && apt update
  ignore_errors: yes
  tags: aptrepo

- name: Add kubernetes repo key
  apt_key:
    url:  https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
    state: present

- name: Install kubernetes repo
  shell: echo "deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Add docker repo key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Install docker repo
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install base tools
  apt:
    name: 
      - wget
      - net-tools
      - dnsutils
      - bash-completion
      - telnet
      - curl
      - lrzsz
      - jq
      - linux-tools-common
      - strace 
      - vim 
      - iotop
      - dnsmasq
      - iproute2
      - nfs-common
      - python3-selinux
      - policycoreutils
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - network-manager
    update_cache: yes
  tags: install-base-tools

