- name: Install ipvsadm
  yum:
    name:
      - ipvsadm
      - ipset
      - sysstat
      - conntrack
      - libseccomp
  tags: ipvs

- name: Modprode Kernel Module for IPVS
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4
  tags:
    - ipvs
