---
# tasks file for host-init

##########
# CentOS #
# ########
- include: yum.yml
  when: OS_ID == "centos" or OS_ID == "rocky"
- include: apt.yml
  when: OS_ID == "ubuntu"
- include: selinux.yml
  when: OS_ID == "centos"
- include: update.yml
  when: is_system_update
- include: ulimit.yml
- include: ipvs.yml
- include: sysctl.yml
- include: swap.yml
- include: centos_ssh.yml
- include: chronyd.yml
  when: chronyd_install
- include: hostname.yml
- include: docker.yml
- include: installKubeadm.yml
- include: apiServerDns.yml
  when: master_vip is defined
- include: resolv.yml
  when: public_network_node == False and OS_ID == "centos"
- include: publicInterface.yml
  when: public_network_node == True
- include: reboot.yml
  when: is_system_update
