- name: Enabled NetworkManager
  service: name=NetworkManager state=started enabled=yes

- name: Configure the public network card
  shell: nmcli connection add type tun ifname pip0 con-name pip0 mode tap ip4 {{ advertise_address }}/32
  tags: publicNetwork
