- name: yum update
  command: yum update -y --exclude=kubelet --exclude=kubeadm --exclude=docker --exclude=runc
  tags: yum-update
  when: OS_ID == "centos"

- name: apt upgrade
  apt:
    only_upgrade: yes
  when: OS_ID == "ubuntu"
